DELETE FROM schmetzer_scores_all WHERE season = {year};

INSERT INTO schmetzer_scores_all (
    id,
    season,
    player_name,
    player_nationality,
    position,
    squad,
    player_age,
    player_yob,
    nineties,
    schmetzer_score,
    schmetzer_rk,
    aerial_duels_won,
    aerial_duels_won_pts,
    aerial_duels_lost,
    aerial_duels_lost_pts,
    aerial_duels_total,
    aerial_duels_total_pts,
    aerial_duels_won_pct,
    tackles_won,
    tackles_won_pts,
    interceptions,
    interceptions_pts,
    recoveries,
    recoveries_pts
)
SELECT
    id,
    {year} AS season,
    player_name,
    player_nationality,
    position,
    squad,
    player_age,
    player_yob,
    nineties,
    schmetzer_score,
    schmetzer_rk,
    aerial_duels_won,
    aerial_duels_won_pts,
    aerial_duels_lost,
    aerial_duels_lost_pts,
    aerial_duels_total,
    aerial_duels_total_pts,
    aerial_duels_won_pct,
    tackles_won,
    tackles_won_pts,
    interceptions,
    interceptions_pts,
    recoveries,
    recoveries_pts
FROM schmetzer_scores_{year};
